// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Grpc.Core {
  public static partial class ThingsToDo
  {
    static readonly string __ServiceName = "Grpc.Core.ThingsToDo";

    static readonly grpc::Marshaller<global::Grpc.Core.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Core.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpc.Core.HelloReply> __Marshaller_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Core.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpc.Core.HelloRequest, global::Grpc.Core.HelloReply> __Method_SayHello = new grpc::Method<global::Grpc.Core.HelloRequest, global::Grpc.Core.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpc.Core.HelloReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ThingsToDo</summary>
    public abstract partial class ThingsToDoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Grpc.Core.HelloReply> SayHello(global::Grpc.Core.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ThingsToDo</summary>
    public partial class ThingsToDoClient : grpc::ClientBase<ThingsToDoClient>
    {
      /// <summary>Creates a new client for ThingsToDo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ThingsToDoClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ThingsToDo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ThingsToDoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ThingsToDoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ThingsToDoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Grpc.Core.HelloReply SayHello(global::Grpc.Core.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.Core.HelloReply SayHello(global::Grpc.Core.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Core.HelloReply> SayHelloAsync(global::Grpc.Core.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Core.HelloReply> SayHelloAsync(global::Grpc.Core.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ThingsToDoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ThingsToDoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ThingsToDoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

  }
}
#endregion
